### ISSUE TITLE
Trying to schedule an Image to Instagram I get the following error:

### ISSUE THREAD

**Issue by rustyflakes** [thepostcode/nextpost#1]
media URL not valid
Media is squared and .jpg so it should be ok for Instagram.

error_log displays the following:
[03-Apr-2017 22:52:37 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'sample@email.tst' for key 'email'' in /home/apoixrar/public_html/app/vendor/usmanhalalit/pixie/src/Pixie/QueryBuilder/QueryBuilderHandler.php:152
Stack trace:
#0 /home/apoixrar/public_html/app/vendor/usmanhalalit/pixie/src/Pixie/QueryBuilder/QueryBuilderHandler.php(152): PDOStatement->execute()
#1 /home/apoixrar/public_html/app/vendor/usmanhalalit/pixie/src/Pixie/QueryBuilder/QueryBuilderHandler.php(325): Pixie\QueryBuilder\QueryBuilderHandler->statement('INSERT INTO `np...', Array)
#2 /home/apoixrar/public_html/app/vendor/usmanhalalit/pixie/src/Pixie/QueryBuilder/QueryBuilderHandler.php(356): Pixie\QueryBuilder\QueryBuilderHandler->doInsert(Array, 'insert')
#3 /home/apoixrar/public_html/app/models/UserModel.php(116): Pixie\QueryBuilder\QueryBuilderHandler->insert(Array)
#4 /home/apoixrar/public_html/app/core/DataEntry.php(190): UserModel->insert()
#5 /home/apoixrar/public_html/app/controller in /home/apoixrar/public_html/app/vendor/usmanhalalit/pixie/src/Pixie/QueryBuilder/QueryBuilderHandler.php on line 152

**Comment by rustyflakes** [comment]
I found the BUG

1.  uploaded the photo using the browse button.
2.  the name of the file on my computer was "Benny wag.jpg", it was uploaded as "Benny frenchie.jpg" using the browse button in /post.
3. When I selected the photo the Img URL displayed "http://www.mysite.com/assets/uploads/1/Benny Wag.jpg"
4. The space Between Benny and Wag was causing the problem.
it should of import the addres from your app used to upload files to nextpost app like: ....uploads/1/Benny%20Wag.jpg

can you fix this? @thepostcode 
Thanks.

**Comment by thepostcode** [comment]
Sorry I didn't get it, you say script automatically renamed your file from "Benny wag.jpg" to "Benny frenchie.jpg"?

**Comment by rustyflakes** [comment]
> Benny wag.jpg" to "Benny frenchie.jpg"?
sorry, My mistake. 

Look at the sequence of images. Notice what's the name of the file recently uploaded.

![screen shot 2017-04-04 at 9 39 49 am](https://cloud.githubusercontent.com/assets/16108718/24672094/aa2a0e2a-1941-11e7-8f95-53870e07daeb.png)
![screen shot 2017-04-04 at 9 39 58 am](https://cloud.githubusercontent.com/assets/16108718/24672096/aa2b974a-1941-11e7-80f9-cf23ef0c08f1.png)
![screen shot 2017-04-04 at 9 40 52 am](https://cloud.githubusercontent.com/assets/16108718/24672098/aa2d3f64-1941-11e7-83ba-e18097e12699.png)
![screen shot 2017-04-04 at 9 42 18 am](https://cloud.githubusercontent.com/assets/16108718/24672097/aa2bc346-1941-11e7-81f7-d1323f969073.png)
![screen shot 2017-04-04 at 9 42 26 am](https://cloud.githubusercontent.com/assets/16108718/24672095/aa2a58da-1941-11e7-8265-178429b08c8c.png)

**Comment by thepostcode** [comment]
Thanks for reporting this bug.  Please make following changes to fix this error:

1. Change the code line 85 on `/app/controllers/PostController.php` as below:
```php
if (!filter_var(str_replace(" ", "%20", Input::post("media_url")), FILTER_VALIDATE_URL)) {
```   


2. Change the code line 14 on `/app/controllers/InstagramController.php` as below:
```php
if (filter_var(str_replace(" ", "%20", $Post->get("media_url")), FILTER_VALIDATE_URL)) {
```
