### ISSUE TITLE
Logo images shouldn't be converted to JPEG

### ISSUE THREAD

**Issue by vorujov** [thepostcode/nextpost#12]
Images uploaded from Logo Update page should remain as is

**Comment by vorujov** [comment]
There is an issue in logo update page. Uploaded image should not be converted to JPEG.

**Comment by mdimannyit** [comment]
I am having the same issue!

**Comment by vorujov** [comment]
Yes, I confirm this bug. I'll update the script in a day or two with minor bugs fixed. Currently it seems there are only two minor bugs.

**Comment by thepostcode** [comment]
This issue has been fixed in v3.0.1
