### ISSUE TITLE
Missing pages after installation

### ISSUE THREAD

**Issue by SBYDeveloper** [thepostcode/nextpost#17]
Hello, I just made a purchase and done every step from the installation process. As I finished it I went to the newly created website and now I can not log in or sign up. When I click on log in im getting this error File not found (404 error)
If you think what you're looking for should be here, please contact the site owner.

**Comment by thepostcode** [comment]
Hi there,

Please create a new support ticket at http://support.getnextpost.io with your purchase code.

**Comment by Domikulka** [comment]
Hello, I have same problem. Do you know where was problem? Any solve? Thank you
