### ISSUE TITLE
Errors after install

### ISSUE THREAD

**Issue by sptrm2** [thepostcode/nextpost#21]
I just purchased NextPost and loaded all files to the public directory here: https://assets.sptrm.com/nextpost/

It is not working, getting a HTTP 500 error. 

The logs show the following error:
[11-Oct-2017 11:02:21] PHP Parse error:  syntax error, unexpected '[' in ***/nextpost/index.php on line 61

Please advise

**Comment by sptrm2** [comment]
Is anyone watching these posts?

**Comment by 1pnb** [comment]
Looks like a problem with PHP version (need to be 5.6 or above) or PHP modules on your server.

**Comment by sptrm2** [comment]
Thanks for the help. Updating that enabled us to get to the installation page. However, I am still not able to get the installation to complete. It kept giving me an error that it could not connect to the database (I verified all of our settings are correct 3 times.) Now, after trying the “finish installation” a few times, it is giving me this error:
This license has been exceeded max allowed use count.

Please help me get this working.

Thanks,
Brad

**Comment by sptrm2** [comment]
? please help

**Comment by 1pnb** [comment]
I am just another user of NextPost, everything is working fine. 

This license has been exceeded max allowed use count may mean that you have a pending installation on another server/domain name (?)

**Comment by sptrm2** [comment]
Thanks, but we don't have another server/domain name. This is the only location we have even attempted installation on.

**Comment by sptrm2** [comment]
Really frustrated that this is stuck and I'm not getting support. I guess I'll ask for a refund if I don't get a response this week.

**Comment by 1pnb** [comment]
Looks like somewhere a record on your license is stuck (?) Try installing on a fresh server maybe. Also, try emailing the author or posting on forum, I am sure they will respond.

**Comment by vorujov** [comment]
Hello sptrm2,

"This license has been exceeded max allowed use count" - this error happens after few several failed installation. Please create a new private ticket at http://support.getnextpost.io with your purchase code to reset your license key.
