### ISSUE TITLE
Auto Follow doesn't work

### ISSUE THREAD

**Issue by ssgemici** [thepostcode/nextpost#24]
I installed Auto Follow module. I changed setting as Slow - 60 req/hour, I checked Enable Random Delay. I opened module page, search for some hashtags ad people. Pause not selected. Then Save. But after about 6 hours, there is no action yet. :( What should I do?

**Comment by Timonna** [comment]
Same here. Not working. Even likes too..

**Comment by ssgemici** [comment]
I found the solution : http://docs.getnextpost.io/scheduling.php

**Comment by Timonna** [comment]
thank you i found it too. but it didn't work for me. thanks anyway.

**Comment by vorujov** [comment]
Hello Timonna,

I hope you've already fixed it. If not, please create a new ticket at http://support.getnextpost.io
