### ISSUE TITLE
Are Scheduled Photos and Post Now Photos Different Formats?

### ISSUE THREAD

**Issue by rustyflakes** [thepostcode/nextpost#3]
Hi, I scheduled a photo that I uploaded through "ElFinder".
It wasn't published at the specified time. ERROR in the Database Showed: {"msg":"InstagramAPI\\ConfigureResponse : Uploaded image isn't in the right format"}

But I used the same media to Post it Immediately and it was Published.

What do you think is the problem?

Here are screenshots of the Problem in nextpost dashboard and in the database.

I tested the same photo  in 2 different accounts ( 1 scheduled post [failed] and 1 post now [success] in each

![screen shot 2017-04-05 at 9 19 15 am](https://cloud.githubusercontent.com/assets/16108718/24707951/6e76a5f8-19e3-11e7-97bd-d1ad67297462.png)
![screen shot 2017-04-05 at 9 36 38 am](https://cloud.githubusercontent.com/assets/16108718/24707952/6e76b430-19e3-11e7-9fc0-503dad400dc4.png)

**Comment by thepostcode** [comment]
No both of Post now and Schedule functions uses same methods to publish the photos to Instagram. So such an error is unexpected. Please contact us with email to check and fix the error.

**Comment by rustyflakes** [comment]
This is one of the images I am having problems uploading http://www.instakite.com/assets/uploads/1/dropbox/Ready/rustyflakes-untitled%20shoot-003.jpg

**Comment by vorujov** [comment]
#1
