### ISSUE TITLE
Lenguage Issue under Prices

### ISSUE THREAD

**Issue by mdimannyit** [thepostcode/nextpost#4]
It says : pre month instead of per month.

**Comment by rustyflakes** [comment]
Go to Index.php under the Theme Folder.
and change the code below, located in the **div class="package-list clearfix">**
`<span class="per"><?= __("**per** month") ?></span>`

**Comment by mdimannyit** [comment]
Thanks!

**Comment by thepostcode** [comment]
Thanks for reporting! You can correct it either as in @rustyflakes's answer or updating the line 684 on /app/locale/en_US/messages.po
