### ISSUE TITLE
Posting To account but not appearing in Instagram

### ISSUE THREAD

**Issue by rustyflakes** [thepostcode/nextpost#6]
Hi, I am posting to an account but they are not appearing on instagram.
Message says Succesfull
Database says: {"msg":"Published successfully!","individual_responses":[{"status":"published","msg":"Published successfully!","account":"bennythefrenchiedog","code":"BShoBdcDQmI"}]}

**Comment by thepostcode** [comment]
Hi, probably Instagram removes your image right after publishing. This might be caused by the content of image. In this case, there is nothing to do with the script.

**Comment by rustyflakes** [comment]
I uploaded the same photo to Instagram using their app and it was allowed.
