### ISSUE TITLE
Time shows different in Posted and Scheduled view

### ISSUE THREAD

**Issue by rustyflakes** [thepostcode/nextpost#7]
I selected NewYork Time Zone when creating the account.
When I schedule the post and go to My scheduled and Posted View.
The time shows different than what I choosed.

see photo (proof in the post of bottom right of the screen)
 
![screen shot 2017-04-07 at 11 32 25 am](https://cloud.githubusercontent.com/assets/16108718/24807737/6abdc856-1b87-11e7-8865-1e9aafbf7051.png)

**Comment by vorujov** [comment]
Thanks you very much for reporting this error. Here is the fix:

1. Open /app/views/fragments/scheduled-posts.fragment.php
2.  Change the line `116` as below:

```php
<?php 
    $d = new \Moment\Moment($p->get("publish_date"), date_default_timezone_get());
    $d->setTimezone($AuthUser->get("time_zone"));
?>
```
